#!/bin/bash
make clean
#
#  buildable platforms of somewhat questionable support level
# make lilypad
make BAUD_RATE=9600 pro8
make BAUD_RATE=9600 pro16
make BAUD_RATE=9600 pro20
make BAUD_RATE=9600 atmega328_pro8
# make BAUD_RATE=9600 sanguino
# make BAUD_RATE=9600 mega1280
# make BAUD_RATE=9600 luminet
# make BAUD_RATE=9600 diecimila
# make BAUD_RATE=9600 bobuino
# make BAUD_RATE=9600 wildfirev2
make BAUD_RATE=9600 atmega1284
make BAUD_RATE=9600 atmega32
make BAUD_RATE=9600 atmega88
make BAUD_RATE=9600 atmega168p

#
# Atmel development board targets
# make BAUD_RATE=9600 xplained168pb
# make BAUD_RATE=9600 xplained328p
# make BAUD_RATE=9600 xplained328pb

#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
make BAUD_RATE=9600 atmega8
make BAUD_RATE=9600 atmega168
make BAUD_RATE=9600 atmega328
